version: '3.5'

services:

  # php-fpm
  php-fpm:
    container_name: portal-php-fpm
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    volumes:
      - ./:/var/www/html
      - ~/.composer:/root/.composer/cache

  # nginx
  nginx:
    container_name: assetic-nginx
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: .docker/nginx/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    volumes:
      - ./:/var/www/html
    ports:
      - 3107:80
    depends_on:
      - php-fpm